### PR TITLE
Combined navigation links and added email submission form (Conflicts resolved)

### PR DESCRIPTION
**Pull request by Pr0ftR3gret**
If accepted I'll work on a generator function for this nav bar.

### CODE REVIEW

**Comment by Pr0ftR3gret** [comment]
Screenshot_20191004_102212

**Comment by DiscoverSquishy** [comment]
@Pr0ftR3gret There seems to be merge conflicts, we can’t merge this unless GitHub gives the green light.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Pr0ftR3gret** [comment]
Should be resolved again.

**Comment by MattCSmith** [comment]
Closing this PR, as its been partially implemented already. Feel free to reopen if the need arises

**Pull request closed without merging**
