### PR TITLE
Fix to addition of Santa Claus: The Movie

### PR DESCRIPTION
**Pull request by jpk3lly**
The film was appearing on the list twice and the film details were also on screen permanently.

### CODE REVIEW

**Comment by MattCSmith** [comment]
Hey @jpk3lly 
Nice job on the PR, Unfortunately there is a conflict preventing me from merging this PR, it would be awesome if you could resolve and push.

This is likely to have happened due to the sheer number of PRs coming in today, but always make sure you pull changes from the upstream before pushing and making a PR. 😄

**Comment by jpk3lly** [comment]
No probs, i will try and get that resolved. Probably when my kids are in bed

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MattCSmith** [comment]
Closing this PR as conflicts are still present and content is probably outdated. Feel free to reopen should you be able to resolve 😄

**Comment by jpk3lly** [comment]
Thats cool, when i went on to fix it looked like someone else had already beaten me to it, i should have closed the pull request off at that point. Sorry

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
