### PR TITLE
[Conflict Resolved] Add Navlink generator for nav dropdown

### PR DESCRIPTION
**Pull request by CouchCat**
#208 

* Add generic script to generate links for dropdown
* Update navbar styles
* Refactor navbar section of all pages

### CODE REVIEW

**Comment by CouchCat** [comment]
@SamirJouni I hopefully fixed all bugs and conflicts this time

**Comment by CouchCat** [comment]
@SamirJouni This should be the one. I feel it!

**Comment by DiscoverSquishy** [comment]
@CouchCat There seems to be merge conflicts, we can’t merge this unless GitHub gives the green light.

Tip: It shows up under your commits if it’s a go or not :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CouchCat** [comment]
@DiscoverSquishy Thanks for the reply! This time I'm seeing green stuff

**Comment by CouchCat** [comment]
@SamirJouni @DiscoverSquishy  Am I doing something wrong? I have been fixing the conflicts a couple times now but it seems that maybe PR merged before mine are turning my PR in to a conflicting one? Could you please check the PRs labeled with "Conflict Present" first before the ones without any labels? ... Maybe I am being silly going the wrong direction here  🤷‍♂️

Screen Shot 2019-10-06 at 02 38 53

Here's Github giving me the green light, just in case.

**Comment by CouchCat** [comment]
@SamirJouni @DiscoverSquishy 
Fixed the conflict again as usual. As a humble request, could you please check the PRs labeled with "Conflict Present" first so that they may finally be done.

Thanks!!

Screen Shot 2019-10-06 at 19 05 43

**Comment by SamirJouni** [comment]
Great, you fixed the problem. Yeah my bad, I hope I didn't give you too much trouble with the new conflicts caused by merges of newer pull request. That was kinda unfair. Good suggestion though!

**Comment by CouchCat** [comment]
@SamirJouni Thank you so much for resolving this!! Also thank you very much for supervising this project! 👏👏👏

**Comment by CouchCat** [comment]
Closes #208

**Pull request merged**
